APPL_DATA_PATH = "res/aapl-60-min-data.txt"

AAPL_FIGURE_TITLE = "AAPL - 60 min NASDAQ"

DATE_FORMAT = "%m/%d/%Y"
TIME_FORMAT = "%H:%M"
DATETIME_FORMAT = DATE_FORMAT + " " + TIME_FORMAT

TIME_COLUMN = "Time"
DATE_COLUMN = "Date"
DATETIME_COLUMN = "DateTime"
HIGH_COLUMN = "High"
LOW_COLUMN = "Low"
CLOSE_COLUMN = "Close"
UP_COLUMN = "Up"
DOWN_COLUMN = "Down"

BOLLINGER_PERIOD = 20
BOLLINGER_MULTIPLIER = 2

TRADING_FEE = 0.02
