MSFT_DATA_PATH = "res/msft-daily-data.txt"
AAPL_DATA_PATH = "res/aapl-daily-data.txt"
BP_DATA_PATH = "res/bp-daily-data.txt"

MSFT_TITLE = "MSFT - Daily NASDAQ Price (USD)"
AAPL_TITLE = "AAPL - Daily NASDAQ Price (USD)"
BP_TITLE = "BP - Daily NASDAQ Price (USD)"

DATE_FORMAT = "%m/%d/%Y"
TIME_FORMAT = "%H:%M"
DATETIME_FORMAT = DATE_FORMAT + " " + TIME_FORMAT

TIME_COLUMN = "Time"
DATE_COLUMN = "Date"
DATETIME_COLUMN = "DateTime"
HIGH_COLUMN = "High"
LOW_COLUMN = "Low"
CLOSE_COLUMN = "Close"
UP_COLUMN = "Up"
DOWN_COLUMN = "Down"

BOLLINGER_PERIOD = 20
BOLLINGER_MULTIPLIER = 2

TRADING_FEE = 5
NO_OF_SHARES = 100

LONG_STOP_LOSS_FACTOR = 0.2
SHORT_STOP_LOSS_FACTOR = 0.1
